spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_test_db
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
