spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=postgres
spring.datasource.password=gust@v09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

## Etapa 4 — Estrutura de pastas do Backend

